### ISSUE TITLE
installation difficulty

### ISSUE THREAD

**Issue by legolass73** [Bu1k/ProvisioningAPI#2]
Hello, I have problems with the installation of the module, would it be possible to have a text or video tutorial?

**Comment by xaoseric** [comment]
This project is still a work in progress, which is likely why you are having issues.

**Comment by legolass73** [comment]
maybe even tried to explain to me how to install it even if it's under development and it's more or less unstable?

**Comment by legolass73** [comment]
Hello, I would like to know how to install the module?

**Comment by xaoseric** [comment]
Install documents will be available soon.
